version: '3'
services:
  # ------ Load balancing and Reverse proxy ------
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - user
      - greenhouse
      - moisture
      - humidity
  # ------ MQTT broker ------
  broker:
    image: emitter/server
    ports:
      - "8080:8080"
    env_file:
      - ./broker/emitter.env
  # ------ Web application interface ------
  web:
    build: ./web
    volumes:
      - ./web/public:/usr/share/nginx/html
  # ------ User service ------
  user:
    build: ./user
    volumes:
      - ./user:/usr/src/app
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    depends_on:
      - db
    restart: on-failure
  # ------ Greenhouse service ------
  greenhouse:
    build: ./greenhouse
    volumes:
      - ./greenhouse:/usr/src/app
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    depends_on:
      - db
    restart: on-failure
  # ------ Main DB ------
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
  # ------ Moisture service ------
  moisture:
    build: ./moisture
    volumes:
      - ./moisture:/usr/src/app
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    depends_on:
      - db-moisture
    restart: on-failure
  db-moisture:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27018:27017"
  # ------ Humidity service ------
  humidity:
    build: ./humidity
    volumes:
      - ./humidity:/usr/src/app
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    depends_on:
      - db-humidity
    restart: on-failure
  db-humidity:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27019:27017"
