version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - moisture
      - humidity
  web:
    build: ./web
    volumes:
      - ./web/public:/usr/share/nginx/html
  moisture:
    build: ./moisture
    volumes:
      - ./moisture:/usr/src/app
  humidity:
    build: ./humidity
    volumes:
      - ./humidity:/usr/src/app
  broker:
    image: emitter/server
    ports:
      - "8080:8080"
    env_file:
      - ./broker/emitter.env
